services:
  - type: web
    name: fastmcp-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/server.py
    plan: free
    autoDeploy: false
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DB_URL
        value: https://raw.githubusercontent.com/chitadi/news-agent-poke-mcp/data/newsletter.db